# @package _group_

topiocqa_train_rewrites_t5_qrecc:
  _target_: dpr.data.biencoder_data.JsonQADataset
  file: data.retriever.topiocqa-rewrites-t5-qrecc-train.json

topiocqa_dev_rewrites_t5_qrecc:
  _target_: dpr.data.biencoder_data.JsonQADataset
  file: data.retriever.topiocqa-rewrites-t5-qrecc-dev.json

topiocqa_train_original:
  _target_: dpr.data.biencoder_data.JsonQADataset
  file: data.retriever.topiocqa-original-train.json

topiocqa_dev_original:
  _target_: dpr.data.biencoder_data.JsonQADataset
  file: data.retriever.topiocqa-original-dev.json

topiocqa_train_all_history:
  _target_: dpr.data.biencoder_data.JsonQADataset
  file: data.retriever.topiocqa-all-history-train.json

topiocqa_dev_all_history:
  _target_: dpr.data.biencoder_data.JsonQADataset
  file: data.retriever.topiocqa-all-history-dev.json

